# Generated by Django 5.2.7 on 2025-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("COCINA", "Cocina"),
                    ("MESERO", "Mesero"),
                    ("CAJA", "Caja"),
                    ("ADMIN", "Administrador"),
                ],
                default="MESERO",
                max_length=20,
            ),
        ),
    ]
